version: '3.7'

services:
  prod:
    container_name: impossible_prod
    build:
      context: .
      dockerfile: Dockerfile.prod

  dev:
    container_name: impossible_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true